# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

# https://docs.readthedocs.io/en/stable/config-file/v2.html#build
build:
  os: "ubuntu-24.04"
  tools:
    python: "3.14"

# https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx
sphinx:
  configuration: docs/conf.py

# https://docs.readthedocs.io/en/stable/config-file/v2.html#python
python:
  install:
    # pip-compile --output-file=docs/requirements.txt docs/requirements.in pyproject.toml
    - requirements: docs/requirements.txt
    - method: pip
      path: .
