"""
This type stub file was generated by pyright.
"""

__version__ = ...
def get_include(): # -> list[LiteralString | Unknown]:
    """
    Returns a list of header include paths (for lxml itself, libxml2
    and libxslt) needed to compile C code against lxml if it was built
    with statically linked libraries.
    """
    ...

